### ISSUE TITLE
Публичное Rest API (26-05-2022)

### ISSUE THREAD

**Issue by hdfkjghdfguerdsfd32eeer** [a-yarohovich/capsula-api-docs#1]
// Почему только высота и нет ширины и глубины?
Ширина и глубина сейчас фиксированы. В дальнейшем ширина возможно будет переменной, но тогда и можно будет добавить.

// order_id больше нет в параметрах запроса, он только в ответе. Или он нужен по какой-то причине в параметрах?
Не понял вопрос. id есть в запросе и в ответе.

// [26.05] Вместо code, используется pin, так как code забронировано под код результата
ок

// [26.05] В отличии от версии в текущей документации используется метод DELETE
ок

// [26.05] Не нашел в API как отменить бронирование для возврата заказа.
Да, это не учтено, надо будет добавить

// [26.05] На какой период бронируется ячейка для возврата заказа, не вижу в результате.
Бессрочно, но да, надо сделать ограничение.

**Comment by a-yarohovich** [comment]
> // Почему только высота и нет ширины и глубины?
Ширина и глубина сейчас фиксированы. В дальнейшем ширина возможно будет переменной, но тогда и можно будет добавить.

Тут понятно.

> // order_id больше нет в параметрах запроса, он только в ответе. Или он нужен по какой-то причине в параметрах?
Не понял вопрос. id есть в запросе и в ответе.

Это важный момент - в текущей версии API параметр `order_id` (`id` по старому) присылает клиентский сервис и он несет ответственность за его создание (у тебя даже есть специальный код - `id_not_unique`). Если нет какой-то необходимости в том, чтобы клиент это делал - то генерировать код должен сервер АПИ. Генерация на стороне клиента может применяться в следующем случае - например у нас есть асинхронная событийная система или RPC-calls, где вызов метода со стороны клиента потом генерирует несколько событий или rpc-ответ и клиенту нужно фильтровать его события по этому коду. Такое например используется в rabbit и известно как correlation_id (https://www.rabbitmq.com/tutorials/tutorial-six-java.html).
У тебя же не так - только простой синхронный вызов, поэтому параметр id передавать не нужно, сервер сам его сгенерирует и вернет в ответе, см. https://github.com/a-yarohovich/capsula-api-docs/blob/main/rest-api.md#71-%D0%B7%D0%B0%D0%B1%D1%80%D0%BE%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%BC%D0%B5%D1%81%D1%82%D0%BE-%D0%B4%D0%BB%D1%8F-%D1%80%D0%B0%D0%B7%D0%BC%D0%B5%D1%89%D0%B5%D0%BD%D0%B8%D1%8F-%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D0%B0


> // [26.05] Не нашел в API как отменить бронирование для возврата заказа.
Да, это не учтено, надо будет добавить
> // [26.05] На какой период бронируется ячейка для возврата заказа, не вижу в результате.
Бессрочно, но да, надо сделать ограничение.

Это я добавлю в рамках этого issue

**Comment by a-yarohovich** [comment]
* Для отмена заказа добавил метод https://github.com/a-yarohovich/capsula-api-docs/blob/main/rest-api.md#74-%D0%BE%D1%82%D0%BC%D0%B5%D0%BD%D0%B8%D1%82%D1%8C-%D0%B2%D0%BE%D0%B7%D0%B2%D1%80%D0%B0%D1%82
* Добавил период бронирования для возврата

**Comment by hdfkjghdfguerdsfd32eeer** [comment]
// order_id больше нет в параметрах запроса, он только в ответе. Или он нужен по какой-то причине в параметрах?
Важно, чтобы order_id отправлял клиентский сервис при запросе. Т.к. список order_id хранится на стороне клиента и используется в их системе для идентификации заказа и последующей работы с ним (размещение, выдача, возврат, обработка рекламаций). Т.е. не получится генерить order_id на своей стороне.

**Comment by a-yarohovich** [comment]
> // order_id больше нет в параметрах запроса, он только в ответе. Или он нужен по какой-то причине в параметрах?
Важно, чтобы order_id отправлял клиентский сервис при запросе. Т.к. список order_id хранится на стороне клиента и используется в их системе для идентификации заказа и последующей работы с ним (размещение, выдача, возврат, обработка рекламаций). Т.е. не получится генерить order_id на своей стороне.

Готово
