### ISSUE TITLE
Обсуждение по методу "Получить актуальные данные по заказу"

### ISSUE THREAD

**Issue by a-yarohovich** [a-yarohovich/capsula-api-docs#2]
[Добавил новый метод](https://github.com/a-yarohovich/capsula-api-docs/blob/main/rest-api.md#75-%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B8%D1%82%D1%8C-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D1%8E-%D0%BE-%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D0%B5)

Уточнения относительно текущей документации:
- `order_id` теперь STRING (максимальный размер 128 символов)
- Везде в документе поле `datetime` заменено на более понятное `when_created`
- В выдачу добавил поля: `period`, `when_created`

**Comment by hdfkjghdfguerdsfd32eeer** [comment]
>> order_id теперь STRING (максимальный размер 128 символов)
>> Везде в документе поле datetime заменено на более понятное when_created
>> В выдачу добавил поля: period, when_created
ок, вопросов нет.
