### ISSUE TITLE
Обсуждение GET запросов на получение списка заказов и историю

### ISSUE THREAD

**Issue by a-yarohovich** [a-yarohovich/capsula-api-docs#3]
Добавил еще два запроса
[История статусов](https://github.com/a-yarohovich/capsula-api-docs/blob/main/rest-api.md#76-%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B8%D1%82%D1%8C-%D0%B8%D1%81%D1%82%D0%BE%D1%80%D0%B8%D1%8E-%D1%81%D1%82%D0%B0%D1%82%D1%83%D1%81%D0%BE%D0%B2-%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D0%B0)
[Список заказов](https://github.com/a-yarohovich/capsula-api-docs/blob/main/rest-api.md#77-%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B8%D1%82%D1%8C-%D1%81%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D0%BE%D0%B2)

Получение списка заказов: 
- Объединил все запросы в один запрос с параметрами фильтрации вида `api/v1/orders?status={string}`, где status может принимать значения `all` - все заказы, `actual` - ожидающие получения клиентом, `expired` - просроченные клиентом, `booked` - для которых забронировано место, `returned` - возвращенные клиентом заказы( тут поясни плиз как ты сейчас понимаешь, что этот заказ вернули, я никакого статуса подходящего не вижу)
- Запрос с пагинацией. Добавлены параметры `per_page`, `page`
- Нельзя сделать выборку старше определенного времени но можно моложе. Пока выставил в 3 месяца лимит. Параметр `since`.
- Возможно имеет смысл сделать поле height в миллиметрах? Невозможна ситуация, когда размер может не быть кратен сантиметру?
- Параметр `period` может сделать в минутах или секундах? Невозможна ситуация, когда бронь не кратна суткам?
- Выделил объект заказа в документации в [отдельный раздел](https://github.com/a-yarohovich/capsula-api-docs/blob/main/rest-api.md#61-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82-%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D0%B0)

**Comment by hdfkjghdfguerdsfd32eeer** [comment]
>>Возможно имеет смысл сделать поле height в миллиметрах? Невозможна ситуация, когда размер может не быть кратен сантиметру?
- Клиенты передают с округлением до сантиметра и Capsula измеряет размер также с точностью до сантиментра. Поэтому оставляем сантиметры.

>> Параметр period может сделать в минутах или секундах? Невозможна ситуация, когда бронь не кратна суткам?
- Бронь может быть кратна только суткам.

По остальным пунктам согласен.

**Comment by a-yarohovich** [comment]
Хорошо, принято
